                                                                    
                                                                     
                                             
DROP TABLE TURK.RESULTS_ASSIGNMENTS
/
CREATE TABLE TURK.RESULTS_ASSIGNMENTS
(
    ASSIGNMENTID       VARCHAR2(40 CHAR)   NOT NULL,
    HITID              VARCHAR2(32 CHAR)   NOT NULL,
    WORKERID           VARCHAR2(32 CHAR)   NOT NULL,
    ASSIGNMENTSTATUS   VARCHAR2(10 CHAR)       NULL,
    CATEGORY           VARCHAR2(512 CHAR)      NULL,
    MCOMMENT           VARCHAR2(2048 CHAR)     NULL,
    CATEGORYSUGGESTION VARCHAR2(512 CHAR)      NULL,
    ACCEPTTIME         DATE                    NULL,
    SUBMITTIME         DATE                    NULL,
    AUTOAPPROVALTIME   DATE                    NULL,
    APPROVALTIME       DATE                    NULL,
    REJECTIONTIME      DATE                    NULL,
    REQUESTERFEEDBACK  VARCHAR2(2048 CHAR)     NULL,
    WORKTIMEINSECONDS  NUMBER(*,0)             NULL
)
ORGANIZATION HEAP
TABLESPACE TS_TURK
LOGGING
PCTFREE 10
PCTUSED 0
INITRANS 1
MAXTRANS 255
STORAGE(BUFFER_POOL DEFAULT)
NOPARALLEL
NOCACHE
NOROWDEPENDENCIES
/
ALTER TABLE TURK.RESULTS_ASSIGNMENTS
    DROP CONSTRAINT SYS_C0011940
/
ALTER TABLE TURK.RESULTS_ASSIGNMENTS
    ADD CONSTRAINT SYS_C0011940
    PRIMARY KEY (ASSIGNMENTID)
    USING INDEX TABLESPACE TS_TURK
                PCTFREE 10
                INITRANS 2
                MAXTRANS 255
                STORAGE(INITIAL 80K
                        BUFFER_POOL DEFAULT)
    LOGGING
    ENABLE
    VALIDATE
/


DROP TABLE TURK.RESULTS_HITS
/
CREATE TABLE TURK.RESULTS_HITS
(
    HITID               VARCHAR2(32 CHAR)   NOT NULL,
    HITTYPEID           VARCHAR2(32 CHAR)   NOT NULL,
    REQUESTERANNOTATION VARCHAR2(2048 CHAR)     NULL,
    EXTERNALURL         VARCHAR2(1024 CHAR)     NULL,
    CREATIONTIME        DATE                    NULL,
    EXPIRATION          DATE                    NULL,
    MAXASSIGNMENTS      NUMBER(*,0)             NULL,
    NUMBEROFSIMILARHITS NUMBER(*,0)             NULL
)
ORGANIZATION HEAP
TABLESPACE TS_TURK
LOGGING
PCTFREE 10
PCTUSED 0
INITRANS 1
MAXTRANS 255
STORAGE(BUFFER_POOL DEFAULT)
NOPARALLEL
NOCACHE
NOROWDEPENDENCIES
/
ALTER TABLE TURK.RESULTS_HITS
    DROP CONSTRAINT SYS_C0011936
/
ALTER TABLE TURK.RESULTS_HITS
    ADD CONSTRAINT SYS_C0011936
    PRIMARY KEY (HITID)
    USING INDEX TABLESPACE TS_TURK
                PCTFREE 10
                INITRANS 2
                MAXTRANS 255
                STORAGE(INITIAL 80K
                        BUFFER_POOL DEFAULT)
    LOGGING
    ENABLE
    VALIDATE
/



DROP TABLE TURK.RESULTS_HITTYPES
/
CREATE TABLE TURK.RESULTS_HITTYPES
(
    HITTYPEID                   VARCHAR2(32 CHAR)   NOT NULL,
    TITLE                       VARCHAR2(1024 CHAR)     NULL,
    DESCRIPTION                 VARCHAR2(4000 CHAR)     NULL,
    KEYWORDS                    VARCHAR2(4000 CHAR)     NULL,
    REWARD                      NUMBER(10,2)            NULL,
    ASSIGNMENTDURATIONINSECONDS NUMBER(*,0)             NULL,
    AUTOAPPROVALDELAYINSECONDS  NUMBER(*,0)             NULL
)
ORGANIZATION HEAP
TABLESPACE TS_TURK
LOGGING
PCTFREE 10
PCTUSED 0
INITRANS 1
MAXTRANS 255
STORAGE(BUFFER_POOL DEFAULT)
NOPARALLEL
NOCACHE
NOROWDEPENDENCIES
/
ALTER TABLE TURK.RESULTS_HITTYPES
    DROP CONSTRAINT SYS_C0011942
/
ALTER TABLE TURK.RESULTS_HITTYPES
    ADD CONSTRAINT SYS_C0011942
    PRIMARY KEY (HITTYPEID)
    USING INDEX TABLESPACE TS_TURK
                PCTFREE 10
                INITRANS 2
                MAXTRANS 255
                STORAGE(INITIAL 80K
                        BUFFER_POOL DEFAULT)
    LOGGING
    ENABLE
    VALIDATE
/



DROP TABLE TURK.RESULTS_QUESTIONS
/
CREATE TABLE TURK.RESULTS_QUESTIONS
(
    HITID     VARCHAR2(32 CHAR)   NOT NULL,
    IMAGEURI  VARCHAR2(1024 CHAR) NOT NULL,
    OID       VARCHAR2(512 CHAR)      NULL,
    TITLE     VARCHAR2(512 CHAR)      NULL,
    PRODUCT   VARCHAR2(512 CHAR)      NULL,
    CATEGORY1 VARCHAR2(512 CHAR)      NULL,
    CATEGORY2 VARCHAR2(512 CHAR)      NULL,
    CATEGORY3 VARCHAR2(512 CHAR)      NULL,
    CATEGORY4 VARCHAR2(512 CHAR)      NULL,
    CATEGORY5 VARCHAR2(512 CHAR)      NULL,
    CATEGORY6 VARCHAR2(512 CHAR)      NULL,
    CATEGORY7 VARCHAR2(512 CHAR)      NULL,
    CATEGORY8 VARCHAR2(512 CHAR)      NULL,
    CATEGORY9 VARCHAR2(512 CHAR)      NULL
)
ORGANIZATION HEAP
TABLESPACE TS_TURK
LOGGING
PCTFREE 10
PCTUSED 0
INITRANS 1
MAXTRANS 255
STORAGE(BUFFER_POOL DEFAULT)
NOPARALLEL
NOCACHE
NOROWDEPENDENCIES
/
ALTER TABLE TURK.RESULTS_QUESTIONS
    DROP CONSTRAINT SYS_C0011945
/
ALTER TABLE TURK.RESULTS_QUESTIONS
    ADD CONSTRAINT SYS_C0011945
    PRIMARY KEY (HITID)
    USING INDEX TABLESPACE TS_TURK
                PCTFREE 10
                INITRANS 2
                MAXTRANS 255
                STORAGE(INITIAL 80K
                        BUFFER_POOL DEFAULT)
    LOGGING
    ENABLE
    VALIDATE
/
